# Generated by Django 3.0.3 on 2020-03-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='starter_user',
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
